### ISSUE TITLE
vanillajs-datepicker@1.2.0, brakse scss build, webpack 5, mini-css-extract-plugin

### ISSUE THREAD

**Issue by edgar0011** [mymth/vanillajs-datepicker#96]
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "...ize-base * math": expected expression (e.g. 1px, bold), was ".div(7, 8);"
        on line 53 of node_modules/vanillajs-datepicker/sass/datepicker.scss
        from line 69 of node_modules/vanillajs-datepicker/sass/datepicker-bulma.scss
        from line 6 of src/index.scss
>> -shrinked-width: $dp-cell-size-base * math.div(7, 8);

   ------------------------------------------^

webpack config:

      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: !isProdServer,
            },
          },
          'resolve-url-loader',
          'postcss-loader',
          {
            loader: 'sass-loader',
            options: {
              sourceMap: !isProdServer,
            },
          },
        ],
      },

**Comment by mymth** [comment]
I think you use node-sass and migrating to [dart sass](https://www.npmjs.com/package/sass) should solve the problem.

I did a test build using #87's setup with some modifications to use v1.2 and your webpack config, and was able compile successfully with only one warning from resolve-url-loader about source map configuration.

It's been a while since node-sass became deprecated. I highly recommend switching to dart sass.
And in case you're unfamiliar with `math.div(7, 8)`, it's dart sass's way to write division operation. If it's written as `7 / 8`, dart sass warns that using `/` as a division operator is deprecated. FYI.

**Comment by ddzmichal** [comment]
`SassError: Invalid CSS after "...ize-base * math": expected expression (e.g. 1px, bold), was ".div(7, 8);"
            on line 53 of node_modules/vanillajs-datepicker/sass/datepicker.scss
            from line 4 of src/assets/styles/style.scss
    >> -shrinked-width: $dp-cell-size-base * math.div(7, 8);`
    
 i have the same problem. adding additional settings in webpack does not fix this problem
 
 `{
        // scss
        test: /\.scss$/,
        use: [
          'style-loader',
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: { sourceMap: true },
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: true,
              config: { path: './postcss.config.js' },
            },
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true,
              sassOptions: {
                importer: globImporter(),
                includePaths: [
                  path.resolve(__dirname, './node_modules'),
                ],
              },
            },
          },
        ],
      },`

This solution does not work. Anyone else have any ideas ?

**Comment by Comediant24** [comment]
When building a project on rails, I also encountered this problem.
There were no build errors on 1.1.4

This error appeared after updating the version to 1.2.0

___

> ERROR in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/lib??ref--5-3!./node_modules/sass-loader/lib/loader.js??ref--5-4!./node_modules/vanillajs-datepicker/sass/datepicker.scss
> [08:33:59]       01 Module build failed: 
> [08:33:59]       01 $dp-cell-shrinked-width: $dp-cell-size-base * math.div(7, 8);
> [08:33:59]       01                                                  ^
> [08:33:59]       01       Invalid CSS after "...ize-base * math": expected expression (e.g. 1px, bold), was ".div(7, 8);"
> [08:33:59]       01       in /home/blizko/sites/blizko/releases/20220114082027/node_modules/vanillajs-datepicker/sass/datepicker.scss (line 53, column 51)
> [08:33:59]       01  @ ./node_modules/vanillajs-datepicker/sass/datepicker.scss 2:14-166
> [08:33:59]       01  @ ./node_modules/@apress/apress-frontend-utils/utils/datepicker/datepicker.js
> [08:33:59]       01  @ ./frontend/packs/blizko/assets/desktop/portal/catalogue_show.js
> [08:33:59]       01 
> [08:33:59]       01 ERROR in ./node_modules/vanillajs-datepicker/sass/datepicker.scss
> [08:33:59]       01 Module build failed: ModuleBuildError: Module build failed: 
> [08:33:59]       01 $dp-cell-shrinked-width: $dp-cell-size-base * math.div(7, 8);
> [08:33:59]       01                                                  ^
> [08:33:59]       01       Invalid CSS after "...ize-base * math": expected expression (e.g. 1px, bold), was ".div(7, 8);"
> [08:33:59]       01       in /home/blizko/sites/blizko/releases/20220114082027/node_modules/vanillajs-datepicker/sass/datepicker.scss (line 53, column 51)

**Comment by ddzmichal** [comment]
I blocked on package.json version that one
`"vanillajs-datepicker": "1.1.4",`
and working normally

**Comment by mymth** [comment]
I've just updated the [change log](https://github.com/mymth/vanillajs-datepicker/blob/master/CHANGELOG.md).

Since I have no intention to add backward compatibility for software already deprecated, that compile error will never be fixed through this library's update.

**Comment by mymth** [comment]
For poeple who like to use v1.2 but have to stick with node-sass for some reason,  

If you don't use Bootstrap 5, you can do it with the following:
1. update to v1.2
```sh
npm i -D vanillajs-datepicker@latest
```
2. install v1.1 as vanillajs-datepicker-11
```sh
npm i -D vanillajs-datepicker-11@mpm:vanillajs-datepicker@1.1.4
```
3. change your sass stylesheet's import path to the one of v1.1
```css
@import 'path/to/node_modules/vanillajs-datepicker-11/sass/datepicker';
```

In terms of style, there are no changes in v1.2.0. All the chages made on the stylesheets are adding bs5 stylesheet and update for dart sass syntax. Thus, unless your CSS framework is BS5, there should be no problem with using v1.1's stylesheet with v1.2's JS.
